name: 'Serverless package'

on:
  push:
    paths:
    - '**/source/**'

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - name: Upload packages
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: eu-west-1
        AWS_BUCKET_NAME: ec-lambda-deploy
      run: |
        files=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep '/source/')
        declare -A directories
        python3 -m pip install --upgrade pip
        pip3 install awscli

        for f in $files; do
          dir=$(dirname $f)

          if [ -z ${directories[$dir]} ]; then
            pushd $dir
            pip3 install -r requirements.txt --target .
            zip -r ${dir%%/*}.zip *
            aws s3 cp ${dir%%/*}.zip s3://${AWS_BUCKET_NAME}/${dir%%/*}.zip
            aws lambda get-function --function-name ${dir%%/*} > /dev/null 2>&1

            if [ "$?" -eq 0 ]; then
              aws lambda update-function-code --function-name ${dir%%/*} --s3-bucket ${AWS_BUCKET_NAME} --s3-key ${dir%%/*}.zip
            fi

            popd
            directories[$dir]="done"
          fi

        done
