name: 'Serverless package'

on:
  push:
    paths:
    - '**/source/**'

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        files=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep '/source/')
        declare -A directories
        python -m pip install --upgrade pip

        for f in $files; do
          dir=$(dirname $f)
          if [ -z ${directories[dir]} ]; then
            pushd $dir
            pip install -r requirements.txt --target .
            zip -r function.zip *
            ls -l
            popd
          fi
        done
    #- name: Install dependencies
    #  - run: |
    #      python -m pip install --upgrade pip
    #      pip install -r requirements.txt --target .
    #- name: Upload to S3
    #  uses: actions/aws/cli@master
    #  with:
    #    args: s3 cp serverless/gocode.zip s3://battle-of-runaterra-lambda-dev/
    #  env:
    #      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
    #      AWS_DEFAULT_REGION: us-east-1
    #- name: Update lambda code
    #  uses: actions/aws/cli@master
    #  with:
    #    args: lambda update-function-code --function-name BattleOfRuneterraDev --s3-bucket battle-of-runaterra-lambda-dev --s3-key gocode.zip
    #  env:
    #      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
    #      AWS_DEFAULT_REGION: us-east-1
